In [13]:
import cv2
import numpy as np

In [14]:
faceDetector=cv2.CascadeClassifier('/home/lov/Documents/lbpfacedetection')

In [15]:
def capture():
    cam=cv2.VideoCapture(0)
    id=int(input('PLEASE ENTER THE USER ID:'))
    SampleNum=0
    ret,img=cam.read()
    print(img)
    while(True):
        ret,img=cam.read()
        gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        faces=faceDetector.detectMultiScale(gray,1.2,5)
        for(x,y,w,h) in faces:
            SampleNum+=1
            cv2.imwrite('dataset/user.'+str(id)+'.'+str(SampleNum)+'.jpg',gray[y:y+h,x:x+w])
            cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
            cv2.waitKey(100)
        cv2.imshow('Face',img)
        cv2.waitKey(1)
        if(SampleNum>40):
            break
    cam.release()
    cv2.destroyAllWindows()

In [16]:
capture()

PLEASE ENTER THE USER ID:5
[[[ 75  87  85]
  [ 71  83  81]
  [ 70  83  79]
  ...
  [ 61  75  66]
  [ 63  78  69]
  [ 60  74  65]]

 [[ 73  84  84]
  [ 70  81  82]
  [ 69  81  79]
  ...
  [ 61  76  65]
  [ 61  75  66]
  [ 60  74  65]]

 [[ 70  81  82]
  [ 69  80  81]
  [ 68  79  80]
  ...
  [ 60  79  64]
  [ 59  76  66]
  [ 60  77  67]]

 ...

 [[ 56  62  72]
  [ 56  62  72]
  [ 57  60  71]
  ...
  [103 147 167]
  [101 145 175]
  [ 99 144 173]]

 [[ 57  63  73]
  [ 56  62  72]
  [ 58  61  72]
  ...
  [ 97 149 168]
  [ 96 148 176]
  [ 95 147 175]]

 [[ 59  62  73]
  [ 58  61  72]
  [ 58  64  67]
  ...
  [ 98 151 169]
  [ 98 147 176]
  [ 98 147 176]]]
